import type { Tradition, Artisan, Story, Category, IndianState } from './types';

export const categories: Category[] = [
  { id: '1', name: 'Folk Art', slug: 'folk-art', description: 'Traditional paintings, murals and visual folk expressions', icon: 'Palette', entry_count: 18 },
  { id: '2', name: 'Handicrafts', slug: 'handicrafts', description: 'Handmade crafts, pottery, weaving and textile traditions', icon: 'Hammer', entry_count: 24 },
  { id: '3', name: 'Festivals', slug: 'festivals', description: 'Regional festivals, rituals and seasonal celebrations', icon: 'PartyPopper', entry_count: 15 },
  { id: '4', name: 'Folk Music', slug: 'folk-music', description: 'Regional musical traditions, instruments and ballads', icon: 'Music', entry_count: 12 },
  { id: '5', name: 'Dance', slug: 'dance', description: 'Classical and folk dance forms from across India', icon: 'PersonStanding', entry_count: 16 },
  { id: '6', name: 'Food', slug: 'food', description: 'Regional cuisines, recipes and culinary heritage', icon: 'UtensilsCrossed', entry_count: 20 },
  { id: '7', name: 'Oral History', slug: 'oral-history', description: 'Spoken traditions, folklore, myths and legends', icon: 'BookOpen', entry_count: 14 },
  { id: '8', name: 'Architecture', slug: 'architecture', description: 'Traditional building styles, temples and monuments', icon: 'Building2', entry_count: 10 },
];

export const traditions: Tradition[] = [
  {
    id: 'phad-painting',
    name: 'Phad Painting',
    state: 'Rajasthan',
    district: 'Bhilwara',
    category: 'Folk Art',
    language: 'Rajasthani',
    description: 'Phad painting is a centuries-old folk art form from Rajasthan where artists paint long scrolls depicting the heroic deeds of local deities like Pabuji and Dev Narayan. These vibrant scrolls are traditionally carried by Bhopa priest-singers who perform the stories while unfurling the painted cloth before village audiences at night.',
    history: [
      { year: '14th Century', event: 'Origins traced to the epic of Pabuji, a local Rajasthani deity' },
      { year: '16th Century', event: 'Dev Narayan tradition flourishes, expanding the Phad repertoire' },
      { year: '1960s', event: 'Shrilal Joshi pioneers single-painting Phad for wider audiences' },
      { year: '2017', event: 'Recognized with National Award; exhibited internationally' },
    ],
    location: 'Bhilwara and Shahpura, Rajasthan',
    cover_image: 'https://images.pexels.com/photos/368727/pexels-photo-368727.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/368727/pexels-photo-368727.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/29625840/pexels-photo-29625840.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/22820070/pexels-photo-22820070.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/30108529/pexels-photo-30108529.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/36817155/pexels-photo-36817155.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/22820076/pexels-photo-22820076.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    how_its_made: [
      { step: 'Preparing the Cloth', description: 'A long piece of cotton cloth is starched and polished to create a smooth painting surface.', image: 'https://images.pexels.com/photos/368727/pexels-photo-368727.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Drawing the Outline', description: 'Artists draw the entire composition freehand using a fine brush, without any preliminary sketches.', image: 'https://images.pexels.com/photos/22820070/pexels-photo-22820070.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Applying Colors', description: 'Natural mineral colors are applied in a specific order — orange, then yellow, then green, then blue, then red.', image: 'https://images.pexels.com/photos/30108529/pexels-photo-30108529.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Adding Details', description: 'Fine details, facial features, and decorative borders are painted with precision.', image: 'https://images.pexels.com/photos/36817155/pexels-photo-36817155.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Final Outlines', description: 'Black outlines are applied last to define every figure and element, completing the Phad.', image: 'https://images.pexels.com/photos/22820076/pexels-photo-22820076.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
    ],
    artisan_name: 'Ramesh Kumar Joshi',
    artisan_bio: 'A third-generation Phad painter from Shahpura, Ramesh has been practicing this art for over 35 years. He learned the tradition from his father and grandfather, and has exhibited his work in galleries across India and Europe. He runs a small workshop training young artists in the traditional methods.',
    artisan_image: 'https://images.pexels.com/photos/29400421/pexels-photo-29400421.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan_location: 'Shahpura, Bhilwara, Rajasthan',
  },
  {
    id: 'chhau-dance',
    name: 'Chhau Dance',
    state: 'Jharkhand',
    district: 'Seraikela',
    category: 'Dance',
    language: 'Hindi',
    description: 'Chhau is a semi-classical Indian dance with martial, tribal and folk roots, traditionally performed during the spring festival of Chaitra Parva. Dancers wear elaborate masks and enact stories from the Ramayana and Mahabharata through powerful, athletic movements. The Seraikela style is known for its sophisticated mask work and graceful choreography.',
    history: [
      { year: 'Ancient', event: 'Roots in martial arts traditions of eastern India' },
      { year: '18th Century', event: 'Royal patronage under the Singh Deo dynasty of Seraikela' },
      { year: '1947', event: 'Post-independence revival and wider recognition' },
      { year: '2010', event: 'UNESCO inscribes Chhau on the Representative List of Intangible Cultural Heritage' },
    ],
    location: 'Seraikela-Kharsawan, Jharkhand',
    cover_image: 'https://images.pexels.com/photos/18086354/pexels-photo-18086354.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/18086354/pexels-photo-18086354.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/32285696/pexels-photo-32285696.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/28518032/pexels-photo-28518032.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/35736415/pexels-photo-35736415.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/26856873/pexels-photo-26856873.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/36121661/pexels-photo-36121661.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    how_its_made: [
      { step: 'Crafting the Mask', description: 'Masks are sculpted from clay, paper, and cloth, then painted with expressive features representing mythological characters.', image: 'https://images.pexels.com/photos/20220747/pexels-photo-20220747.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Training the Body', description: 'Dancers undergo years of martial arts training to build the strength and agility required for the athletic movements.', image: 'https://images.pexels.com/photos/18086354/pexels-photo-18086354.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Learning Choreography', description: 'Specific movements and gestures are learned for each character, from the gentle Radha to the fierce Ravana.', image: 'https://images.pexels.com/photos/35736415/pexels-photo-35736415.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Performance', description: 'Performed at night with traditional drum and flute accompaniment during the Chaitra Parva festival.', image: 'https://images.pexels.com/photos/26856873/pexels-photo-26856873.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
    ],
    artisan_name: 'Sudarsan Mahapatra',
    artisan_bio: 'A master Chhau dancer and mask maker from Seraikela, Sudarsan has performed across India and at international festivals. He has dedicated his life to preserving both the dance form and the intricate mask-making craft that accompanies it.',
    artisan_image: 'https://images.pexels.com/photos/30928625/pexels-photo-30928625.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan_location: 'Seraikela, Jharkhand',
  },
  {
    id: 'majuli-mask-making',
    name: 'Majuli Mask Making',
    state: 'Assam',
    district: 'Majuli',
    category: 'Handicrafts',
    language: 'Assamese',
    description: 'Majuli, the largest river island in the world, is home to a unique mask-making tradition used in the Sattriya dance-dramas of Assamese Vaishnavite monasteries. These masks, made from bamboo, clay, and natural colors, depict characters from Hindu mythology and are central to the Bhaona performances held in the island\'s satras (monasteries).',
    history: [
      { year: '16th Century', event: 'Srimanta Sankardeva establishes the Vaishnavite tradition in Majuli' },
      { year: '17th Century', event: 'Mask-making becomes integral to Bhaona performances' },
      { year: '20th Century', event: 'Majuli recognized as a center of Neo-Vaishnavite culture' },
      { year: '2016', event: 'Majuli declared the first island district of India; mask-making gains national attention' },
    ],
    location: 'Majuli Island, Assam',
    cover_image: 'https://images.pexels.com/photos/38571807/pexels-photo-38571807.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/38571807/pexels-photo-38571807.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/20220747/pexels-photo-20220747.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/36395505/pexels-photo-36395505.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/38790913/pexels-photo-38790913.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/34009366/pexels-photo-34009366.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/32214847/pexels-photo-32214847.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    how_its_made: [
      { step: 'Bamboo Framework', description: 'A lightweight bamboo frame is shaped to form the basic structure of the mask.', image: 'https://images.pexels.com/photos/38571807/pexels-photo-38571807.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Clay Layering', description: 'Wet clay and cow dung are applied over the frame to build up facial features and textures.', image: 'https://images.pexels.com/photos/20220747/pexels-photo-20220747.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Cloth and Paper', description: 'Layers of cloth and paper are added for durability and a smooth surface.', image: 'https://images.pexels.com/photos/36395505/pexels-photo-36395505.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Painting', description: 'Natural pigments are used to paint the masks with vibrant, expressive colors representing mythological characters.', image: 'https://images.pexels.com/photos/34009366/pexels-photo-34009366.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Final Touches', description: 'Hair, teeth, and decorative elements are added to complete the character\'s appearance.', image: 'https://images.pexels.com/photos/32214847/pexels-photo-32214847.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
    ],
    artisan_name: 'Ananya Devi',
    artisan_bio: 'Ananya Devi is one of the few women mask makers on Majuli Island. She learned the craft from her father, a respected artisan at the Chamaguri Satra. Her masks are used in Bhaona performances across Assam and have been exhibited in museums in Delhi and Kolkata.',
    artisan_image: 'https://images.pexels.com/photos/36818402/pexels-photo-36818402.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan_location: 'Majuli Island, Assam',
  },
  {
    id: 'rogan-art',
    name: 'Rogan Art',
    state: 'Gujarat',
    district: 'Kutch',
    category: 'Folk Art',
    language: 'Gujarati',
    description: 'Rogan art is a rare textile painting technique from Kutch, Gujarat, where castor oil is boiled and colored with natural pigments to create a thick paint that is applied to fabric using a metal stylus. The paint is never brushed on — it is literally pushed and shaped with a rod, creating intricate floral and geometric patterns. Only a handful of families practice this art today.',
    history: [
      { year: 'Ancient', event: 'Believed to have originated from Persia, brought to Kutch by traveling artisans' },
      { year: '19th Century', event: 'The Khatri family of Nirona becomes the sole preserver of the tradition' },
      { year: '2010s', event: 'Rogan art gains international recognition through exhibitions' },
      { year: '2014', event: 'A Rogan painting is gifted to President Obama during a state visit' },
    ],
    location: 'Nirona village, Kutch, Gujarat',
    cover_image: 'https://images.pexels.com/photos/37223288/pexels-photo-37223288.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/37223288/pexels-photo-37223288.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/22820072/pexels-photo-22820072.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/19310342/pexels-photo-19310342.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/38779084/pexels-photo-38779084.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/368727/pexels-photo-368727.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/22820069/pexels-photo-22820069.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    how_its_made: [
      { step: 'Preparing Rogan', description: 'Castor oil is boiled for hours until it forms a thick, colored paste. Natural pigments are mixed in.', image: 'https://images.pexels.com/photos/37223288/pexels-photo-37223288.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Heating the Stylus', description: 'A metal rod (kalam) is heated and used to pick up the rogan paste, which stretches into threads.', image: 'https://images.pexels.com/photos/22820072/pexels-photo-22820072.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Painting Freehand', description: 'The artist pushes the colored paste onto fabric freehand, creating intricate patterns without any sketch.', image: 'https://images.pexels.com/photos/19310342/pexels-photo-19310342.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Folding and Mirroring', description: 'The fabric is folded to create a mirror image, a signature feature of Rogan art.', image: 'https://images.pexels.com/photos/38779084/pexels-photo-38779084.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
    ],
    artisan_name: 'Abdul Rahman Khatri',
    artisan_bio: 'Abdul Rahman belongs to the Khatri family of Nirona — the only family in the world still practicing Rogan art. He learned the craft from his father and has been creating these intricate paintings for over 30 years. His work has been exhibited in galleries from Tokyo to New York.',
    artisan_image: 'https://images.pexels.com/photos/2477362/pexels-photo-2477362.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan_location: 'Nirona, Kutch, Gujarat',
  },
  {
    id: 'tholpavakoothu',
    name: 'Tholpavakoothu',
    state: 'Kerala',
    district: 'Palakkad',
    category: 'Folk Art',
    language: 'Malayalam',
    description: 'Tholpavakoothu is a traditional shadow puppet theatre from Kerala, performed in temples dedicated to the goddess Bhagavathy. Leather puppets are manipulated behind a screen lit by oil lamps, casting shadows that depict stories from the Ramayana. The performances can last for seven nights, accompanied by recitation and music in a blend of Malayalam and Sanskrit.',
    history: [
      { year: 'Ancient', event: 'Believed to have been brought to Kerala by migrants from Tamil Nadu' },
      { year: '14th Century', event: 'Becomes a regular feature of Bhagavathy temple festivals in Palakkad' },
      { year: '20th Century', event: 'Decline due to changing temple practices and entertainment preferences' },
      { year: '2015', event: 'Revival efforts and inclusion in the Guinness World Record for largest shadow puppet performance' },
    ],
    location: 'Palakkad and Malappuram districts, Kerala',
    cover_image: 'https://images.pexels.com/photos/36470507/pexels-photo-36470507.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/36470507/pexels-photo-36470507.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/12210908/pexels-photo-12210908.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/30259519/pexels-photo-30259519.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/7868580/pexels-photo-7868580.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/16168112/pexels-photo-16168112.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/1583350/pexels-photo-1583350.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    how_its_made: [
      { step: 'Treating the Leather', description: 'Goat or deer skin is treated, stretched, and dried to create the puppet base.', image: 'https://images.pexels.com/photos/36470507/pexels-photo-36470507.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Cutting the Puppet', description: 'Intricate figures are cut from the leather, with joints for movement at the shoulders, elbows, and knees.', image: 'https://images.pexels.com/photos/12210908/pexels-photo-12210908.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Painting', description: 'Puppets are painted with natural colors — each character has a specific color scheme.', image: 'https://images.pexels.com/photos/30259519/pexels-photo-30259519.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Attaching Bamboo Sticks', description: 'Bamboo sticks are attached to the puppets for manipulation behind the screen.', image: 'https://images.pexels.com/photos/7868580/pexels-photo-7868580.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Performance Setup', description: 'A white cloth screen is set up with oil lamps behind it, and puppets are manipulated to cast shadows.', image: 'https://images.pexels.com/photos/1583350/pexels-photo-1583350.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
    ],
    artisan_name: 'Ramachandra Pulavar',
    artisan_bio: 'A master puppeteer from a family that has practiced Tholpavakoothu for generations, Ramachandra has been instrumental in reviving interest in this art form. He runs a puppet museum and training center in Palakkad and has adapted the tradition for contemporary audiences while preserving its ritual roots.',
    artisan_image: 'https://images.pexels.com/photos/32633540/pexels-photo-32633540.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan_location: 'Palakkad, Kerala',
  },
  {
    id: 'baul-music',
    name: 'Baul Music',
    state: 'West Bengal',
    district: 'Birbhum',
    category: 'Folk Music',
    language: 'Bengali',
    description: 'Baul music is the soulful, mystical folk tradition of the Bauls — wandering minstrels of Bengal who sing about love, devotion, and the search for the divine within. With their distinctive single-string ektara and small kettle drum dugi, Bauls express a syncretic philosophy blending Hindu Bhakti and Sufi mysticism. Their songs, passed orally across generations, speak of the human soul\'s journey with raw, poetic simplicity.',
    history: [
      { year: '15th Century', event: 'Baul tradition emerges from the Bhakti and Sufi movements in Bengal' },
      { year: '19th Century', event: 'Lalan Fakir\'s songs define the philosophical core of Baul music' },
      { year: '1960s', event: 'Baul music enters mainstream Bengali culture through artists like Purna Das Baul' },
      { year: '2005', event: 'UNESCO inscribes the Baul tradition on the List of Intangible Cultural Heritage' },
    ],
    location: 'Birbhum and Nadia districts, West Bengal',
    cover_image: 'https://images.pexels.com/photos/15937060/pexels-photo-15937060.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/15937060/pexels-photo-15937060.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/27641014/pexels-photo-27641014.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/32633540/pexels-photo-32633540.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/15937062/pexels-photo-15937062.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/14069974/pexels-photo-14069974.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/14647759/pexels-photo-14647759.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    how_its_made: [
      { step: 'Crafting the Ektara', description: 'A single-string instrument is made from a bamboo neck, gourd body, and string, tuned to a single drone note.', image: 'https://images.pexels.com/photos/15937060/pexels-photo-15937060.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Learning the Songs', description: 'Baul songs are learned orally, passed from guru to disciple without written notation.', image: 'https://images.pexels.com/photos/32633540/pexels-photo-32633540.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'The Wandering Life', description: 'Bauls travel from village to village, singing at fairs, markets, and spiritual gatherings.', image: 'https://images.pexels.com/photos/15937062/pexels-photo-15937062.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Performance', description: 'Songs are performed with ektara, dugi drum, and spontaneous dance, often lasting hours.', image: 'https://images.pexels.com/photos/14069974/pexels-photo-14069974.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
    ],
    artisan_name: 'Lakshman Das Baul',
    artisan_bio: 'Lakshman Das is a wandering Baul singer from Birbhum who has been performing for over 25 years. He travels across Bengal and beyond, singing the songs of Lalan Fakir and other Baul saints. He has performed at major music festivals including the Dover Lane Music Conference and the Rajasthan International Folk Festival.',
    artisan_image: 'https://images.pexels.com/photos/15937062/pexels-photo-15937062.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan_location: 'Birbhum, West Bengal',
  },
  {
    id: 'blue-pottery',
    name: 'Blue Pottery',
    state: 'Rajasthan',
    district: 'Jaipur',
    category: 'Handicrafts',
    language: 'Hindi',
    description: 'Blue pottery is a distinctive craft from Jaipur, known for its blue and turquoise glazes derived from copper oxide. Unlike traditional Indian pottery, it does not use clay — instead, it is made from a mixture of quartz powder, glass, and natural gum. The art form has Persian roots and was brought to Jaipur through Mughal influence.',
    history: [
      { year: '14th Century', event: 'Technique arrives in India via Turkic and Persian craftsmen' },
      { year: '19th Century', event: 'Maharaja Ram Singh II brings the craft to Jaipur and establishes workshops' },
      { year: '1950s', event: 'Kamaladevi Chattopadhyay revives the declining craft' },
      { year: '2009', event: 'Blue pottery receives GI (Geographical Indication) tag for Jaipur' },
    ],
    location: 'Jaipur, Rajasthan',
    cover_image: 'https://images.pexels.com/photos/18977427/pexels-photo-18977427.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/18977427/pexels-photo-18977427.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/34545851/pexels-photo-34545851.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/37014220/pexels-photo-37014220.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/37808898/pexels-photo-37808898.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/37364157/pexels-photo-37364157.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/3145866/pexels-photo-3145866.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    how_its_made: [
      { step: 'Mixing the Dough', description: 'Quartz powder, glass, fuller\'s earth, and natural gum are mixed to form a non-clay dough.', image: 'https://images.pexels.com/photos/3145866/pexels-photo-3145866.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Molding', description: 'The dough is pressed into molds to form bowls, vases, tiles, and other shapes.', image: 'https://images.pexels.com/photos/18977427/pexels-photo-18977427.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Painting', description: 'Designs are painted with mineral oxides — copper oxide for blue, cobalt for darker blue.', image: 'https://images.pexels.com/photos/37014220/pexels-photo-37014220.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Glazing and Firing', description: 'Pieces are dipped in a glaze and fired at low temperatures in traditional kilns.', image: 'https://images.pexels.com/photos/37364157/pexels-photo-37364157.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
    ],
    artisan_name: 'Gopal Saini',
    artisan_bio: 'Gopal Saini is a master blue pottery artisan from Jaipur with over 30 years of experience. He has trained hundreds of artisans in the craft and his work is sold in boutiques across India. He received the State Award for craftsmanship in 2012.',
    artisan_image: 'https://images.pexels.com/photos/10923156/pexels-photo-10923156.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan_location: 'Jaipur, Rajasthan',
  },
  {
    id: 'kalbelia-dance',
    name: 'Kalbelia Dance',
    state: 'Rajasthan',
    district: 'Pali',
    category: 'Dance',
    language: 'Rajasthani',
    description: 'Kalbelia is a sensuous, snake-like folk dance performed by the Kalbelia community of Rajasthan, traditionally snake charmers. Women in flowing black skirts swirl and spin, mimicking the movements of a serpent, while men play the been (a traditional woodwind instrument) and the duf drum. The dance is performed at celebrations and has become an iconic symbol of Rajasthani culture.',
    history: [
      { year: 'Ancient', event: 'Kalbelia community traditionally works as snake catchers and charmers' },
      { year: '20th Century', event: 'Dance form gains recognition beyond the community' },
      { year: '2010', event: 'UNESCO inscribes Kalbelia dance on the Intangible Cultural Heritage list' },
      { year: '2015', event: 'Featured in international cultural festivals and Bollywood films' },
    ],
    location: 'Pali and Barmer districts, Rajasthan',
    cover_image: 'https://images.pexels.com/photos/30424954/pexels-photo-30424954.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/30424954/pexels-photo-30424954.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/32285696/pexels-photo-32285696.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/28518032/pexels-photo-28518032.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/35736415/pexels-photo-35736415.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/36121661/pexels-photo-36121661.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/34717651/pexels-photo-34717651.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    how_its_made: [
      { step: 'Costume Preparation', description: 'Women wear flowing black skirts embroidered with silver and red, representing the black serpent.', image: 'https://images.pexels.com/photos/30424954/pexels-photo-30424954.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Music Setup', description: 'Men play the been (snake-charmer flute) and duf drum, creating hypnotic rhythms.', image: 'https://images.pexels.com/photos/15937060/pexels-photo-15937060.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'The Dance', description: 'Women spin, sway, and arch their bodies in serpent-like movements, their skirts swirling dramatically.', image: 'https://images.pexels.com/photos/35736415/pexels-photo-35736415.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Climax', description: 'The tempo builds to a climax with rapid spinning and acrobatic movements.', image: 'https://images.pexels.com/photos/36121661/pexels-photo-36121661.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
    ],
    artisan_name: 'Gulabo Sapera',
    artisan_bio: 'Gulabo Sapera is a legendary Kalbelia dancer who has performed across the world, from the Edinburgh Festival to the Smithsonian Folklife Festival. Born into the Kalbelia community, she has been instrumental in bringing international recognition to the dance form and has trained hundreds of young dancers.',
    artisan_image: 'https://images.pexels.com/photos/35736419/pexels-photo-35736419.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan_location: 'Pali, Rajasthan',
  },
  {
    id: 'kathputli',
    name: 'Kathputli Puppetry',
    state: 'Rajasthan',
    district: 'Jaipur',
    category: 'Folk Art',
    language: 'Rajasthani',
    description: 'Kathputli is the ancient string puppet tradition of Rajasthan, where wooden marionettes dressed in colorful Rajasthani attire tell stories of royal romances, brave warriors, and local legends. Controlled by strings attached to the puppeteer\'s fingers, these puppets dance, fight, and perform acrobatic feats in lively performances accompanied by traditional music and narration.',
    history: [
      { year: 'Ancient', event: 'Kathputli tradition dates back over a thousand years among the Bhat community' },
      { year: '16th Century', event: 'Royal patronage under Rajput kings; performances at court events' },
      { year: '20th Century', event: 'Bhat community travels across India performing at fairs and festivals' },
      { year: '2010s', event: 'Kathputli Colony in Delhi becomes a symbol of urban artisan displacement' },
    ],
    location: 'Jaipur and Nagaur districts, Rajasthan',
    cover_image: 'https://images.pexels.com/photos/16168112/pexels-photo-16168112.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/16168112/pexels-photo-16168112.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/36470507/pexels-photo-36470507.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/30259519/pexels-photo-30259519.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/36511838/pexels-photo-36511838.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/7868580/pexels-photo-7868580.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/38605121/pexels-photo-38605121.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    how_its_made: [
      { step: 'Carving the Puppet', description: 'Wooden heads and hands are carved and painted with expressive faces.', image: 'https://images.pexels.com/photos/16168112/pexels-photo-16168112.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Dressing', description: 'Puppets are dressed in miniature Rajasthani costumes with jewelry and accessories.', image: 'https://images.pexels.com/photos/30259519/pexels-photo-30259519.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Stringing', description: 'Strings are attached to the puppet\'s head, hands, and waist for manipulation.', image: 'https://images.pexels.com/photos/36511838/pexels-photo-36511838.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Performance', description: 'The puppeteer manipulates multiple strings while narrating stories and voicing characters.', image: 'https://images.pexels.com/photos/38605121/pexels-photo-38605121.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
    ],
    artisan_name: 'Bhanwar Lal Bhat',
    artisan_bio: 'Bhanwar Lal belongs to the Bhat community, the traditional puppeteers of Rajasthan. He has been performing Kathputli for over 40 years and has traveled to over 20 countries with his puppet shows. He runs a small workshop in Jaipur where he trains young people in puppet making and performance.',
    artisan_image: 'https://images.pexels.com/photos/29639572/pexels-photo-29639572.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan_location: 'Jaipur, Rajasthan',
  },
  {
    id: 'pattachitra',
    name: 'Pattachitra Painting',
    state: 'Odisha',
    district: 'Puri',
    category: 'Folk Art',
    language: 'Odia',
    description: 'Pattachitra is a traditional cloth-based scroll painting from Odisha, depicting mythological stories from the Jagannath cult and Hindu epics. Artists use natural colors and fine brushwork to create intricate borders, detailed figures, and vibrant scenes. The paintings are traditionally made during the Anavasara period when the deities of the Jagannath Temple rest behind closed doors.',
    history: [
      { year: '5th Century BC', event: 'Origins linked to ancient Bengali-Odia scroll painting traditions' },
      { year: '12th Century', event: 'Flourishes with the Jagannath temple culture in Puri' },
      { year: '20th Century', event: 'Revival through government and cultural organizations' },
      { year: '2008', event: 'Pattachitra receives GI tag for Odisha' },
    ],
    location: 'Raghurajpur village, Puri, Odisha',
    cover_image: 'https://images.pexels.com/photos/22820070/pexels-photo-22820070.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/22820070/pexels-photo-22820070.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/22820076/pexels-photo-22820076.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/368727/pexels-photo-368727.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/22820069/pexels-photo-22820069.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/30108529/pexels-photo-30108529.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/36817155/pexels-photo-36817155.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    how_its_made: [
      { step: 'Preparing the Canvas', description: 'Cotton cloth is coated with a mixture of chalk and gum, then dried and polished.', image: 'https://images.pexels.com/photos/22820070/pexels-photo-22820070.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Drawing Borders', description: 'Decorative borders are drawn first, framing the central composition.', image: 'https://images.pexels.com/photos/22820076/pexels-photo-22820076.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Natural Colors', description: 'Colors are made from minerals, shells, and plants — white from conch shells, red from hingal, yellow from haritali.', image: 'https://images.pexels.com/photos/368727/pexels-photo-368727.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Painting', description: 'Figures and scenes are painted with fine brushes made from buffalo hair and rat hair.', image: 'https://images.pexels.com/photos/30108529/pexels-photo-30108529.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Finishing', description: 'The painting is coated with a natural varnish for durability and sheen.', image: 'https://images.pexels.com/photos/36817155/pexels-photo-36817155.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
    ],
    artisan_name: 'Bibhuti Maharana',
    artisan_bio: 'Bibhuti is a Pattachitra artist from Raghurajpur, the heritage crafts village of Odisha. He has been painting for over 25 years and his work has been exhibited at the National Handicrafts Museum in Delhi. He specializes in the Jagannath and Dashavatara themes.',
    artisan_image: 'https://images.pexels.com/photos/19310342/pexels-photo-19310342.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan_location: 'Raghurajpur, Puri, Odisha',
  },
  {
    id: 'kathakali',
    name: 'Kathakali',
    state: 'Kerala',
    district: 'Thrissur',
    category: 'Dance',
    language: 'Malayalam',
    description: 'Kathakali is one of India\'s most spectacular classical dance-drama forms, originating in Kerala. Performers wear elaborate makeup, towering headgear, and voluminous skirts, enacting stories from Hindu epics through a sophisticated language of gestures, facial expressions, and eye movements. A single performance can last all night, with drummers and vocalists providing the musical accompaniment.',
    history: [
      { year: '17th Century', event: 'Kathakali evolves from earlier temple arts under the patronage of the Raja of Kottarakkara' },
      { year: '18th Century', event: 'Refined and codified by Kaplingattu Nampoothiri under the Raja of Kottayam' },
      { year: '1930s', event: 'Poet Vallathol establishes Kerala Kalamandalam, ensuring preservation' },
      { year: '2000s', event: 'International recognition; performances at major global arts festivals' },
    ],
    location: 'Thrissur and Ernakulam districts, Kerala',
    cover_image: 'https://images.pexels.com/photos/38087959/pexels-photo-38087959.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/38087959/pexels-photo-38087959.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/8566097/pexels-photo-8566097.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/37596960/pexels-photo-37596960.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/31843397/pexels-photo-31843397.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/34717651/pexels-photo-34717651.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/35685774/pexels-photo-35685774.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    how_its_made: [
      { step: 'Makeup (Chutti)', description: 'Elaborate makeup is applied over hours — green for noble characters, red for evil, yellow for women.', image: 'https://images.pexels.com/photos/31843397/pexels-photo-31843397.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Costume', description: 'Heavy skirts, towering headgear, and ornate jewelry transform the performer into a mythological being.', image: 'https://images.pexels.com/photos/38087959/pexels-photo-38087959.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Mudras', description: 'Performers use a codified system of 24 basic mudras (hand gestures) to convey complex meanings.', image: 'https://images.pexels.com/photos/8566097/pexels-photo-8566097.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Facial Expressions', description: 'Intense eye and facial muscle control is used to express nine distinct emotions (navarasas).', image: 'https://images.pexels.com/photos/37596960/pexels-photo-37596960.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Performance', description: 'Drummers and vocalists accompany the performance, which traditionally runs from dusk to dawn.', image: 'https://images.pexels.com/photos/35685774/pexels-photo-35685774.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
    ],
    artisan_name: 'Kalamandalam Gopi',
    artisan_bio: 'Kalamandalam Gopi is one of the most respected Kathakali performers of his generation. Trained at Kerala Kalamandalam, he has performed for over 40 years and is known for his portrayal of noble characters (pacha roles). He teaches at the institution and has trained many of today\'s leading performers.',
    artisan_image: 'https://images.pexels.com/photos/30481580/pexels-photo-30481580.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan_location: 'Thrissur, Kerala',
  },
  {
    id: 'madhubani',
    name: 'Madhubani Painting',
    state: 'Bihar',
    district: 'Mithila',
    category: 'Folk Art',
    language: 'Maithili',
    description: 'Madhubani (or Mithila) painting is a folk art from the Mithila region of Bihar, traditionally created by women on the walls and floors of their homes during festivals and weddings. The paintings feature intricate geometric patterns, nature motifs, and mythological scenes, using natural pigments and dyes. Today, the art has moved to paper and canvas, gaining international recognition.',
    history: [
      { year: 'Ancient', event: 'Tradition linked to the Ramayana — paintings commissioned for Sita\'s wedding to Rama' },
      { year: '20th Century', event: 'Transferred from walls to paper during a drought relief program' },
      { year: '1970s', event: 'Gains national and international recognition through government promotion' },
      { year: '2007', event: 'Madhubani painting receives GI tag for Bihar' },
    ],
    location: 'Mithila region, Madhubani and Darbhanga districts, Bihar',
    cover_image: 'https://images.pexels.com/photos/30108529/pexels-photo-30108529.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/30108529/pexels-photo-30108529.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/368727/pexels-photo-368727.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/22820070/pexels-photo-22820070.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/36817155/pexels-photo-36817155.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/22820076/pexels-photo-22820076.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/38779084/pexels-photo-38779084.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    how_its_made: [
      { step: 'Preparing the Surface', description: 'Traditionally done on walls coated with cow dung and mud; now done on handmade paper.', image: 'https://images.pexels.com/photos/30108529/pexels-photo-30108529.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Outlining', description: 'Artists draw the outline using a bamboo pen (kalam) or brush, without preliminary sketches.', image: 'https://images.pexels.com/photos/368727/pexels-photo-368727.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Filling Colors', description: 'Natural dyes are applied — indigo for blue, turmeric for yellow, kusam flower for red.', image: 'https://images.pexels.com/photos/22820070/pexels-photo-22820070.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Double Lining', description: 'Double-line borders and intricate patterns fill every space — no empty areas are left.', image: 'https://images.pexels.com/photos/36817155/pexels-photo-36817155.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Finishing', description: 'The painting is completed with fine details and decorative elements.', image: 'https://images.pexels.com/photos/22820076/pexels-photo-22820076.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
    ],
    artisan_name: 'Sunita Devi',
    artisan_bio: 'Sunita Devi is a Madhubani artist from the village of Jitwarpur. She learned the art from her mother and grandmother, who painted on the walls of their home. She has exhibited her work at the National Crafts Museum in Delhi and at international exhibitions in Germany and Japan.',
    artisan_image: 'https://images.pexels.com/photos/5874825/pexels-photo-5874825.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan_location: 'Jitwarpur, Madhubani, Bihar',
  },
  {
    id: 'hampi-architecture',
    name: 'Hampi Temple Architecture',
    state: 'Karnataka',
    district: 'Bellary',
    category: 'Architecture',
    language: 'Kannada',
    description: 'Hampi, the ruins of the Vijayanagara Empire\'s capital, is a UNESCO World Heritage Site featuring some of the most spectacular temple architecture in India. The site includes the Virupaksha Temple, Vittala Temple with its iconic stone chariot, and numerous other structures showcasing the Dravidian architectural style at its peak.',
    history: [
      { year: '14th Century', event: 'Vijayanagara Empire establishes Hampi as its capital' },
      { year: '1565', event: 'Empire falls after the Battle of Talikota; city abandoned and in ruins' },
      { year: '1980s', event: 'Archaeological Survey of India begins major restoration' },
      { year: '1986', event: 'UNESCO designates Hampi as a World Heritage Site' },
    ],
    location: 'Hampi, Bellary district, Karnataka',
    cover_image: 'https://images.pexels.com/photos/27719237/pexels-photo-27719237.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    gallery: [
      'https://images.pexels.com/photos/27719237/pexels-photo-27719237.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/28793885/pexels-photo-28793885.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/31969428/pexels-photo-31969428.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/5103732/pexels-photo-5103732.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/31991711/pexels-photo-31991711.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
      'https://images.pexels.com/photos/36924117/pexels-photo-36924117.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    ],
    how_its_made: [
      { step: 'Site Selection', description: 'Temples were built on granite outcrops, integrating natural boulders into the sacred landscape.', image: 'https://images.pexels.com/photos/27719237/pexels-photo-27719237.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Stone Carving', description: 'Master sculptors carved intricate figures and patterns directly into granite blocks.', image: 'https://images.pexels.com/photos/28793885/pexels-photo-28793885.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Assembly', description: 'Blocks were assembled without mortar, using precise interlocking techniques.', image: 'https://images.pexels.com/photos/31969428/pexels-photo-31969428.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
      { step: 'Gopuram Construction', description: 'Towering gateways (gopurams) were built with progressively smaller tiers, covered with sculptures.', image: 'https://images.pexels.com/photos/5103732/pexels-photo-5103732.jpeg?auto=compress&cs=tinysrgb&h=650&w=940' },
    ],
    artisan_name: 'Srinivas Murthy',
    artisan_bio: 'Srinivas Murthy is a traditional stone sculptor from Hampi who has been involved in the restoration work at the UNESCO site for over 20 years. He learned the traditional carving techniques from his father and now trains apprentices in the ASI conservation workshop.',
    artisan_image: 'https://images.pexels.com/photos/30969805/pexels-photo-30969805.jpeg?auto=compress&cs=tinysrgb&h=650&w=940',
    artisan_location: 'Hampi, Bellary, Karnataka',
  },
];

export const artisans: Artisan[] = [
  { id: 'a1', name: 'Ramesh Kumar Joshi', craft: 'Phad Painting', state: 'Rajasthan', district: 'Bhilwara', bio: 'A third-generation Phad painter from Shahpura, Ramesh has been practicing this art for over 35 years. He learned the tradition from his father and grandfather, and has exhibited his work in galleries across India and Europe.', image: 'https://images.pexels.com/photos/29400421/pexels-photo-29400421.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', years_experience: 35, tradition_id: 'phad-painting' },
  { id: 'a2', name: 'Ananya Devi', craft: 'Mask Maker', state: 'Assam', district: 'Majuli', bio: 'One of the few women mask makers on Majuli Island. She learned the craft from her father, a respected artisan at the Chamaguri Satra. Her masks are used in Bhaona performances across Assam.', image: 'https://images.pexels.com/photos/36818402/pexels-photo-36818402.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', years_experience: 18, tradition_id: 'majuli-mask-making' },
  { id: 'a3', name: 'Abdul Rahman Khatri', craft: 'Rogan Artist', state: 'Gujarat', district: 'Kutch', bio: 'Belongs to the Khatri family of Nirona — the only family in the world still practicing Rogan art. He has been creating these intricate paintings for over 30 years and has exhibited from Tokyo to New York.', image: 'https://images.pexels.com/photos/2477362/pexels-photo-2477362.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', years_experience: 30, tradition_id: 'rogan-art' },
  { id: 'a4', name: 'Gulabo Sapera', craft: 'Kalbelia Dancer', state: 'Rajasthan', district: 'Pali', bio: 'A legendary Kalbelia dancer who has performed across the world, from the Edinburgh Festival to the Smithsonian Folklife Festival. She has trained hundreds of young dancers in the community.', image: 'https://images.pexels.com/photos/35736419/pexels-photo-35736419.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', years_experience: 40, tradition_id: 'kalbelia-dance' },
  { id: 'a5', name: 'Kalamandalam Gopi', craft: 'Kathakali Performer', state: 'Kerala', district: 'Thrissur', bio: 'One of the most respected Kathakali performers of his generation. Trained at Kerala Kalamandalam, he has performed for over 40 years and teaches at the institution.', image: 'https://images.pexels.com/photos/30481580/pexels-photo-30481580.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', years_experience: 45, tradition_id: 'kathakali' },
  { id: 'a6', name: 'Bhanwar Lal Bhat', craft: 'Kathputli Puppeteer', state: 'Rajasthan', district: 'Jaipur', bio: 'Belongs to the Bhat community, the traditional puppeteers of Rajasthan. He has been performing Kathputli for over 40 years and has traveled to over 20 countries with his puppet shows.', image: 'https://images.pexels.com/photos/29639572/pexels-photo-29639572.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', years_experience: 40, tradition_id: 'kathputli' },
  { id: 'a7', name: 'Sunita Devi', craft: 'Madhubani Painter', state: 'Bihar', district: 'Madhubani', bio: 'A Madhubani artist from the village of Jitwarpur. She learned the art from her mother and grandmother and has exhibited at the National Crafts Museum in Delhi and internationally in Germany and Japan.', image: 'https://images.pexels.com/photos/5874825/pexels-photo-5874825.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', years_experience: 25, tradition_id: 'madhubani' },
  { id: 'a8', name: 'Srinivas Murthy', craft: 'Stone Sculptor', state: 'Karnataka', district: 'Bellary', bio: 'A traditional stone sculptor from Hampi who has been involved in the restoration work at the UNESCO World Heritage Site for over 20 years. He trains apprentices in the ASI conservation workshop.', image: 'https://images.pexels.com/photos/30969805/pexels-photo-30969805.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', years_experience: 20, tradition_id: 'hampi-architecture' },
];

export const stories: Story[] = [
  { id: 's1', title: 'The Last Phad of Shahpura', tradition_id: 'phad-painting', content: 'In the small town of Shahpura, a 30-foot scroll lies unfurled under the shade of a banyan tree. Ramesh Kumar Joshi has been painting this Phad for six months...', author: 'Meera Sharma', language: 'English', image: 'https://images.pexels.com/photos/368727/pexels-photo-368727.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', reading_time: '8 min', state: 'Rajasthan', category: 'Folk Art' },
  { id: 's2', title: 'Masks of the River Island', tradition_id: 'majuli-mask-making', content: 'On Majuli, the river island that is slowly being swallowed by the Brahmaputra, masks are not just objects of art — they are vessels of the divine...', author: 'Arjun Das', language: 'English', image: 'https://images.pexels.com/photos/38571807/pexels-photo-38571807.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', reading_time: '6 min', state: 'Assam', category: 'Handicrafts' },
  { id: 's3', title: 'The Paint That Stretches Like Thread', tradition_id: 'rogan-art', content: 'In the village of Nirona, in the vast salt desert of Kutch, Abdul Rahman Khatri sits cross-legged before a white cloth. In his hand is a simple metal rod...', author: 'Priya Patel', language: 'English', image: 'https://images.pexels.com/photos/37223288/pexels-photo-37223288.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', reading_time: '7 min', state: 'Gujarat', category: 'Folk Art' },
  { id: 's4', title: 'Dancing Like a Serpent', tradition_id: 'kalbelia-dance', content: 'The black skirt swirls in the dusk light, spinning wider and wider until it seems the dancer herself might take flight. This is Kalbelia...', author: 'Rajesh Kumar', language: 'English', image: 'https://images.pexels.com/photos/30424954/pexels-photo-30424954.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', reading_time: '5 min', state: 'Rajasthan', category: 'Dance' },
  { id: 's5', title: 'Shadows of the Ramayana', tradition_id: 'tholpavakoothu', content: 'Behind a white screen lit by flickering oil lamps, leather puppets dance the Ramayana. This is Tholpavakoothu, Kerala\'s ancient shadow puppet theatre...', author: 'Lakshmi Nair', language: 'English', image: 'https://images.pexels.com/photos/36470507/pexels-photo-36470507.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', reading_time: '9 min', state: 'Kerala', category: 'Folk Art' },
  { id: 's6', title: 'The Wandering Mystics of Bengal', tradition_id: 'baul-music', content: 'With a single-string ektara slung over his shoulder and saffron robes fluttering in the wind, Lakshman Das walks the dusty roads of Birbhum...', author: 'Soumitra Banerjee', language: 'English', image: 'https://images.pexels.com/photos/15937060/pexels-photo-15937060.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', reading_time: '10 min', state: 'West Bengal', category: 'Folk Music' },
  { id: 's7', title: 'The Blue Fire of Jaipur', tradition_id: 'blue-pottery', content: 'In a narrow lane in Jaipur\'s old city, Gopal Saini pulls a glowing blue vase from the kiln. The color is unlike any ceramic glaze — it is the blue of the desert sky...', author: 'Neha Agarwal', language: 'English', image: 'https://images.pexels.com/photos/18977427/pexels-photo-18977427.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', reading_time: '6 min', state: 'Rajasthan', category: 'Handicrafts' },
  { id: 's8', title: 'When the Gods Rest: Pattachitra of Raghurajpur', tradition_id: 'pattachitra', content: 'Every year, for 15 days, the deities of the Jagannath Temple in Puri rest behind closed doors. During this Anavasara period, the village of Raghurajpur comes alive...', author: 'Debasish Mohanty', language: 'English', image: 'https://images.pexels.com/photos/22820070/pexels-photo-22820070.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', reading_time: '8 min', state: 'Odisha', category: 'Folk Art' },
  { id: 's9', title: 'The Stone Chariot That Never Moves', tradition_id: 'hampi-architecture', content: 'In the ruins of Hampi, a stone chariot stands frozen in time. It was built to honor Garuda, the mount of Vishnu, but the wheels never turned...', author: 'Vijay Hegde', language: 'English', image: 'https://images.pexels.com/photos/27719237/pexels-photo-27719237.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', reading_time: '7 min', state: 'Karnataka', category: 'Architecture' },
  { id: 's10', title: 'The Painted Walls of Mithila', tradition_id: 'madhubani', content: 'In the villages of Madhubani, the walls speak. Every home is a canvas, every wall a story. Sunita Devi dips her bamboo pen into a paste of turmeric and lime...', author: 'Anjali Mishra', language: 'English', image: 'https://images.pexels.com/photos/30108529/pexels-photo-30108529.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', reading_time: '6 min', state: 'Bihar', category: 'Folk Art' },
];

export const indianStates: IndianState[] = [
  {
    name: 'Rajasthan',
    region: 'North',
    traditionsCount: 42,
    featuredTraditions: ['Phad Painting', 'Blue Pottery', 'Kalbelia Dance', 'Kathputli'],
    categories: ['Folk Art', 'Handicrafts', 'Dance', 'Folk Music'],
    featuredArtisans: ['Ramesh Kumar Joshi', 'Gulabo Sapera', 'Bhanwar Lal Bhat', 'Gopal Saini'],
  },
  {
    name: 'Kerala',
    region: 'South',
    traditionsCount: 35,
    featuredTraditions: ['Tholpavakoothu', 'Kathakali', 'Mohiniyattam', 'Theyyam'],
    categories: ['Dance', 'Folk Art', 'Folk Music', 'Architecture'],
    featuredArtisans: ['Kalamandalam Gopi', 'Ramachandra Pulavar'],
  },
  {
    name: 'Assam',
    region: 'East',
    traditionsCount: 28,
    featuredTraditions: ['Majuli Mask Making', 'Sattriya Dance', 'Bihu', 'Muga Silk Weaving'],
    categories: ['Handicrafts', 'Dance', 'Festivals', 'Folk Music'],
    featuredArtisans: ['Ananya Devi'],
  },
  {
    name: 'Gujarat',
    region: 'West',
    traditionsCount: 31,
    featuredTraditions: ['Rogan Art', 'Patola Weaving', 'Garba', 'Kutch Embroidery'],
    categories: ['Folk Art', 'Handicrafts', 'Dance', 'Festivals'],
    featuredArtisans: ['Abdul Rahman Khatri'],
  },
  {
    name: 'West Bengal',
    region: 'East',
    traditionsCount: 26,
    featuredTraditions: ['Baul Music', 'Kantha Embroidery', 'Chhau Dance', 'Patachitra'],
    categories: ['Folk Music', 'Handicrafts', 'Dance', 'Folk Art'],
    featuredArtisans: ['Lakshman Das Baul'],
  },
  {
    name: 'Bihar',
    region: 'East',
    traditionsCount: 22,
    featuredTraditions: ['Madhubani Painting', 'Sujini Embroidery', 'Chhau Dance', 'Sama Chakeva'],
    categories: ['Folk Art', 'Handicrafts', 'Destivals', 'Oral History'],
    featuredArtisans: ['Sunita Devi'],
  },
  {
    name: 'Odisha',
    region: 'East',
    traditionsCount: 30,
    featuredTraditions: ['Pattachitra Painting', 'Odissi Dance', 'Sand Art', 'Gotipua'],
    categories: ['Folk Art', 'Dance', 'Handicrafts', 'Architecture'],
    featuredArtisans: ['Bibhuti Maharana'],
  },
  {
    name: 'Karnataka',
    region: 'South',
    traditionsCount: 24,
    featuredTraditions: ['Hampi Temple Architecture', 'Yakshagana', 'Mysore Painting', 'Dollu Kunitha'],
    categories: ['Architecture', 'Dance', 'Folk Art', 'Folk Music'],
    featuredArtisans: ['Srinivas Murthy'],
  },
  {
    name: 'Jharkhand',
    region: 'East',
    traditionsCount: 18,
    featuredTraditions: ['Chhau Dance', 'Sohrai Painting', 'Paitkar Painting', 'Jhumar'],
    categories: ['Dance', 'Folk Art', 'Folk Music', 'Festivals'],
    featuredArtisans: ['Sudarsan Mahapatra'],
  },
];

export const mockContributions = [
  { id: 'c1', title: 'Pithora Painting', state: 'Gujarat', district: 'Panchmahal', category: 'Folk Art', contributor_name: 'Hardik Rathwa', contributor_contact: 'hardik.r@example.com', status: 'pending' as const, created_at: '2026-08-28T10:30:00Z', description: 'Pithora paintings are ritual wall paintings of the Rathwa community.', story: 'My grandfather taught me this art when I was twelve...' },
  { id: 'c2', title: 'Dhimsa Dance', state: 'Andhra Pradesh', district: 'Araku Valley', category: 'Dance', contributor_name: 'Lakshmi Porja', contributor_contact: 'lakshmi.p@example.com', status: 'pending' as const, created_at: '2026-08-30T14:20:00Z', description: 'Dhimsa is a tribal dance performed by the Porja community during festivals.', story: 'Our village has preserved this dance for centuries...' },
  { id: 'c3', title: 'Cherial Scroll Painting', state: 'Telangana', district: 'Warangal', category: 'Folk Art', contributor_name: 'Mallesh Nakash', contributor_contact: 'mallesh.n@example.com', status: 'approved' as const, created_at: '2026-08-20T09:00:00Z', description: 'Cherial scroll painting is a narrative art form used by storytelling communities.', story: 'I am one of the last practitioners of this dying art...' },
  { id: 'c4', title: 'Alpana Floor Art', state: 'West Bengal', district: 'Nadia', category: 'Folk Art', contributor_name: 'Rimeli Sarkar', contributor_contact: 'rimeli.s@example.com', status: 'pending' as const, created_at: '2026-09-01T16:45:00Z', description: 'Alpana is a traditional rice-paste floor painting done during Lakshmi Puja.', story: 'Every autumn, the women of our household wake before dawn...' },
  { id: 'c5', title: 'Toda Embroidery', state: 'Tamil Nadu', district: 'Nilgiris', category: 'Handicrafts', contributor_name: 'Kutti Kuttan', contributor_contact: 'kutti.k@example.com', status: 'rejected' as const, created_at: '2026-08-15T11:00:00Z', description: 'Toda embroidery is a distinctive needlework tradition of the Toda tribal community.', story: 'The patterns represent the buffaloes and the sun...' },
];
